export const coursesData = [
  {
    title: "08 Weeks Professional Makeup And Hair Styling Course",
    slug: "08-weeks-professional-makeup-and-hair-styling",
    duration: "08 Weeks",
    timings: "TBD",
    batch: "TBD",
    image: "/photos/img (33).webp",
    syllabus: [
      "Anatomy of face, Types of skin",
      "Skin prep and prime",
      "Color theory and color mixing",
      "Color correction",
      "Tools & Brushes knowledge",
      "Foundation application and blending techniques",
      "Concealing techniques",
      "Contouring and Highlighting (Cream and Powder)",
      "Eye makeup techniques (Smokey, Cut crease, Halo, etc.)",
      "Eyeliner application (Basic, Winged, Smudged)",
      "False eyelashes application",
      "Eyebrow shaping and filling",
      "Lip shaping and application",
      "Bridal makeup (Traditional, Contemporary, HD)",
      "Airbrush makeup basic knowledge",
      "Hair styling basics (Blow dry, Ironing, Curls)",
      "Bridal hair updos and styling",
      "Product knowledge and vanity setup",
    ],
  },
  {
    title: "06 Weeks Bridal Makeup And Hair Styling Course",
    slug: "06-weeks-bridal-makeup-and-hair-styling",
    duration: "06 Weeks",
    timings: "TBD",
    batch: "TBD",
    image: "/photos/img (34).webp",
    syllabus: [
      "Skin prep and prime for brides",
      "Color theory and color correction",
      "Tools & Brushes knowledge",
      "HD foundation application and blending techniques",
      "Concealing techniques",
      "Contouring and Highlighting (Cream and Powder)",
      "Bridal Eye makeup techniques",
      "Eyeliner application (Basic, Winged, Smudged)",
      "False eyelashes application",
      "Eyebrow shaping and filling",
      "Lip shaping and application",
      "Different types of Bridal makeup (North Indian, South Indian, Catholic, etc.)",
      "Hair styling basics (Blow dry, Ironing, Curls)",
      "Bridal hair updos and styling",
      "Draping (Saree, Dupatta, Lehenga)",
      "Product knowledge and vanity setup",
    ],
  },
  {
    title: "04 Weeks Professional Hair Styling Course",
    slug: "04-weeks-professional-hair-styling",
    duration: "04 Weeks",
    timings: "TBD",
    batch: "TBD",
    image: "/photos/img (35).webp",
    syllabus: [
      "Hair anatomy and structure",
      "Tools and equipment knowledge",
      "Product knowledge (Sprays, Mousse, Serums, etc.)",
      "Basic hair preparation (Blow dry, Ironing, Tonging)",
      "Sectioning techniques",
      "Basic braids (French, Dutch, Fishtail)",
      "Classic updos (Buns, Chignons, French twists)",
      "Bridal hair styling techniques",
      "Vintage hair styling",
      "Creative and avant-garde hair styling",
      "Using hair extensions and padding",
      "Client consultation and communication",
    ],
  },
  {
    title: "Weekend Professional Makeup And Hair Styling Course",
    slug: "weekend-professional-makeup-and-hair-styling",
    duration: "Weekend",
    timings: "TBD",
    batch: "TBD",
    image: "/photos/img (1).webp",
    syllabus: [
      "Skin preparation and priming",
      "Color theory and color correction basics",
      "Foundation application and blending",
      "Basic highlighting and contouring",
      "Everyday and party eye makeup",
      "Eyeliner and mascara application",
      "Lipstick application",
      "Basic hair styling (Blow dry, straight, simple curls)",
      "Quick party hair updos",
      "Product knowledge for personal use",
    ],
  },
  {
    title: "Personal Grooming Course",
    slug: "personal-grooming-course",
    duration: "1-2 Days",
    timings: "TBD",
    batch: "TBD",
    image: "/photos/img (2).webp",
    syllabus: [
      "Flawless base application",
      "Natural day makeup",
      "Evening/Party makeup",
      "Eye makeup techniques (e.g., smokey eyes)",
      "Contouring & Highlighting",
      "Blush & Lip application",
      "Personalized product recommendations",
      "Skin care routine basics",
      "Quick and easy hair styling techniques for everyday",
      "Confidence building and personal styling tips",
    ],
  },
];
